#!/usr/bin/env node
/* Vendor the share cards from the Bookings Desk — and prove the bytes.
 *
 *   node scripts/vendor-share.mjs                 # fetch from source, re-vendor
 *   node scripts/vendor-share.mjs --check         # verify what is committed (offline)
 *   node scripts/vendor-share.mjs --check --remote # re-fetch and fail if drifted
 *
 * WHAT IS VENDORED AND WHY. Two files from bamfs1976-art/pl-bookings, verbatim:
 *
 *   vendor/share.js   PLDShare — the 1080×1350 canvas renderer, its theme
 *                     registry and drawing primitives. Kept byte-identical:
 *                     the desks and this app draw with one implementation.
 *   vendor/save.js    PLDSave — the native share sheet where a phone has one,
 *                     the anchor fallback everywhere else. iOS Safari ignores
 *                     `download` on a blob: URL, so every card that used the
 *                     bare anchor was a dead button on an iPhone.
 *
 * The Gameweek Edge theme and the three adapters (Team of the Week, captain
 * pick, squad rating) live in lib/gwe-share.js, which is first-party and not
 * vendored. They compose a card from PLDShare's exported primitives rather
 * than from its desk cards, because the desk cards' shared footer draws the
 * 18+ / BeGambleAware line that a Gameweek Edge card must never carry; the
 * renderer stays unchanged and the line stays off our cards. See
 * scripts/check-share.mjs for the assertion.
 *
 * Provenance header, payload() split and manifest layout are the same as
 * scripts/vendor-rotation.mjs and scripts/vendor-suspension.mjs.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const VENDOR = join(root, 'vendor');
const MANIFEST = join(root, 'scripts', 'vendor-share.sha256.json');

const check = process.argv.includes('--check');
const remote = process.argv.includes('--remote');

/* Pinned to a commit on main. */
const SOURCE = {
  owner: 'bamfs1976-art',
  repo: 'pl-bookings',
  commit: '34bba4cd8978e0dc9df1327baad8dccee4e71ffd',
  branch: 'main',
};
const RAW = 'https://raw.githubusercontent.com/' + SOURCE.owner + '/' + SOURCE.repo + '/';

const FILES = [
  {
    id: 'share',
    from: 'assets/share.js',
    to: 'share.js',
    what: 'the renderer — PLDShare: themes, primitives and the desk cards, verbatim',
    build: (src) => src,
  },
  {
    id: 'save',
    from: 'assets/save.js',
    to: 'save.js',
    what: 'the saver — PLDSave.file: native share sheet where available, anchor fallback elsewhere, verbatim',
    build: (src) => src,
  },
];

function sha256(s) { return createHash('sha256').update(s, 'utf8').digest('hex'); }

/* ── the provenance header ───────────────────────────────────────────── */
const HEAD_END = ' * ── end vendored header ──';

function header(f, hash, fetched) {
  return [
    '/* VENDORED — do not edit this file.',
    ' *',
    ' * ' + f.what,
    ' *',
    ' * source   ' + SOURCE.owner + '/' + SOURCE.repo + '  ' + f.from,
    ' * commit   ' + SOURCE.commit,
    ' * branch   ' + SOURCE.branch,
    ' * sha256   ' + hash,
    ' * fetched  ' + fetched,
    ' *',
    ' * Re-vendor with: node scripts/vendor-share.mjs',
    ' * Verify with:    node scripts/vendor-share.mjs --check',
    HEAD_END,
    ' */',
    '',
  ].join('\n');
}

function payload(text) {
  const i = text.indexOf(HEAD_END);
  if (i === -1) return text;
  const j = text.indexOf('\n', i);
  const k = text.indexOf('\n', j + 1);
  return text.slice(k + 1);
}

function localPath(f) { return join(VENDOR, f.to); }
function readLocal(f) {
  const p = localPath(f);
  if (!existsSync(p)) throw new Error('vendor/' + f.to + ' is missing. Run: node scripts/vendor-share.mjs');
  return readFileSync(p, 'utf8');
}

/* The source: a local checkout when PL_BOOKINGS_DIR points at one (it must be
   at the pinned commit), otherwise the raw file at the pinned commit. */
async function fetchSource(f) {
  const dir = process.env.PL_BOOKINGS_DIR;
  if (dir) {
    const head = execFileSync('git', ['-C', dir, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
    if (head !== SOURCE.commit) {
      throw new Error('PL_BOOKINGS_DIR is at ' + head.slice(0, 12) + ' but this script pins ' +
        SOURCE.commit.slice(0, 12) + ' — check out the pinned commit or move the pin deliberately');
    }
    return readFileSync(join(dir, f.from), 'utf8');
  }
  const url = RAW + SOURCE.commit + '/' + f.from;
  const r = await fetch(url, { headers: { 'user-agent': 'gameweek-edge/vendor-share' } });
  if (!r.ok) throw new Error('fetching ' + f.from + ' at ' + SOURCE.commit.slice(0, 12) + ' returned HTTP ' + r.status + '\n  ' + url);
  return await r.text();
}

function readManifest() {
  if (!existsSync(MANIFEST)) {
    throw new Error('scripts/vendor-share.sha256.json is missing. Run: node scripts/vendor-share.mjs');
  }
  return JSON.parse(readFileSync(MANIFEST, 'utf8'));
}

async function doVendor() {
  mkdirSync(VENDOR, { recursive: true });
  const fetched = new Date().toISOString().slice(0, 10);
  const man = { commit: SOURCE.commit, branch: SOURCE.branch, files: {} };
  for (const f of FILES) {
    const src = await fetchSource(f);
    const body = f.build(src);
    const hash = sha256(body);
    writeFileSync(localPath(f), header(f, hash, fetched) + body);
    man.files[f.id] = { from: f.from, to: 'vendor/' + f.to, sha256: hash, sourceSha256: sha256(src), fetched };
    console.log('vendored ' + f.from + ' → vendor/' + f.to + '  ' + hash.slice(0, 12));
  }
  writeFileSync(MANIFEST, JSON.stringify(man, null, 2) + '\n');
}

async function doCheck() {
  const man = readManifest();
  let bad = 0;
  if (man.commit !== SOURCE.commit) {
    console.error('the manifest was written against ' + man.commit + ' but this script pins ' + SOURCE.commit);
    bad++;
  }
  for (const f of FILES) {
    const text = readLocal(f);
    const got = sha256(payload(text));
    const rec = man.files && man.files[f.id];
    if (!rec) { console.error('no recorded hash for ' + f.id); bad++; continue; }
    if (got !== rec.sha256) {
      console.error(f.id + ' (vendor/' + f.to + ') does not match the recorded sha256.\n' +
        '  recorded ' + rec.sha256 + '\n  on disk   ' + got + '\n' +
        '  Vendored code is a copy of somebody else\'s rule, byte for byte. Fix it upstream ' +
        'and re-run: node scripts/vendor-share.mjs');
      bad++;
      continue;
    }
    for (const need of [SOURCE.commit, rec.sha256, f.from]) {
      if (!text.includes(need)) { console.error(f.id + ' provenance header does not carry "' + need + '"'); bad++; }
    }
  }
  /* The renderer and the saver must still load with no DOM present, exactly
     as scripts/check-share.mjs loads them; a module that starts touching
     `document` at load time would break the guard and the offline shell. */
  try {
    const ctx = {};
    new Function('window', 'globalThis', payload(readLocal(FILES[0])))(ctx, ctx);
    new Function('window', 'globalThis', payload(readLocal(FILES[1])))(ctx, ctx);
    if (!ctx.PLDShare || typeof ctx.PLDShare.roundRect !== 'function' || !ctx.PLDShare.THEMES) { console.error('vendor/share.js did not export PLDShare with its primitives'); bad++; }
    if (!ctx.PLDSave || typeof ctx.PLDSave.file !== 'function') { console.error('vendor/save.js did not export PLDSave.file'); bad++; }
  } catch (e) { console.error('the vendored share modules did not load: ' + e.message); bad++; }

  if (remote) {
    for (const f of FILES) {
      const want = payload(readLocal(f));
      const there = f.build(await fetchSource(f));
      if (there !== want) {
        console.error(f.id + ' has drifted from ' + SOURCE.owner + '/' + SOURCE.repo + ' ' + f.from +
          ' at ' + SOURCE.commit.slice(0, 12) + '. Re-run: node scripts/vendor-share.mjs');
        bad++;
      }
    }
  }
  if (bad) process.exit(1);
  console.log('vendor-share --check OK: ' + FILES.length + ' files at ' + SOURCE.commit.slice(0, 7) +
    ', every sha256 matching, PLDShare and PLDSave load' + (remote ? ', source unchanged' : ''));
}

(check ? doCheck() : doVendor()).catch((e) => { console.error(e.message); process.exit(1); });
