/*
 * Vendor the display faces used by the evergreen social cards.
 *
 *   node scripts/social/fetch-fonts.mjs
 *
 * Writes scripts/social/fonts/*.woff2 and scripts/social/fonts/fonts.css,
 * which the card templates @import instead of linking to Google Fonts.
 *
 * Why vendor rather than link, when the recap and daily-card templates link:
 * those render on a machine with open network. These cards are committed
 * PNGs — an evergreen asset that has to come out byte-identical whoever
 * re-renders it, including in a sandbox with no route to fonts.gstatic.com.
 * A missing webfont there doesn't fail the render, it silently ships a card
 * set in the fallback face, which is the worst of the three outcomes.
 *
 * Only the latin subset is kept; the cards are British English.
 *
 * Licences: Bricolage Grotesque, Public Sans and JetBrains Mono are all
 * released under the SIL Open Font License 1.1, which permits redistribution
 * — see fonts/README.md, written by this script.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONTS = join(HERE, 'fonts');

const API = 'https://fonts.googleapis.com/css2'
  + '?family=Bricolage+Grotesque:opsz,wght@12..96,600;12..96,800'
  + '&family=Public+Sans:wght@500;600;700;800'
  + '&family=JetBrains+Mono:wght@500;700'
  + '&display=swap';

/* A desktop UA, or the API serves the ttf fallback sheet meant for old
   browsers. curl rather than fetch(): it picks up the proxy environment
   variables on its own, which node's fetch does not. */
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const curl = (url, out) => execFileSync('curl',
  ['-sSfL', '-A', UA, url, ...(out ? ['-o', out] : [])],
  { maxBuffer: 32 * 1024 * 1024, encoding: out ? 'buffer' : 'utf8' });

/* The latin block is the one whose range starts at U+0000 and carries no
   Vietnamese, Cyrillic or Greek codepoints. Matching on that is steadier
   than "take the last block", which is only true by convention. */
const isLatin = (range) => /U\+0000-00FF/.test(range);

mkdirSync(FONTS, { recursive: true });
const css = curl(API);

const blocks = css.split('@font-face').slice(1);
const kept = [];
const seen = new Set();

for (const block of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([\d\s.]+);/.exec(block)?.[1].trim();
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1] ?? '';
  const url = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
  if (!family || !url || !isLatin(range)) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight.replace(/[\s.]+/g, '_')}.woff2`;
  if (seen.has(file)) continue;
  seen.add(file);

  curl(url, join(FONTS, file));
  kept.push(`@font-face {\n  font-family: '${family}';\n  font-style: normal;\n`
    + `  font-weight: ${weight};\n  font-display: block;\n  src: url('./${file}') format('woff2');\n}`);
  console.log(`✓ ${file}`);
}

if (!kept.length) { console.error('No latin faces found — the API response changed shape.'); process.exit(1); }

writeFileSync(join(FONTS, 'fonts.css'),
  '/* Generated by scripts/social/fetch-fonts.mjs — do not edit by hand. */\n'
  + kept.join('\n\n') + '\n');

writeFileSync(join(FONTS, 'README.md'),
  '# Vendored faces\n\n'
  + 'Written by `node scripts/social/fetch-fonts.mjs`. Do not edit by hand.\n\n'
  + 'The evergreen social cards render from committed PNGs, so the faces are\n'
  + 'vendored rather than linked — a card re-rendered on a machine with no route\n'
  + 'to fonts.gstatic.com must come out identical, not silently fall back.\n\n'
  + 'Latin subsets only. All three families are SIL Open Font License 1.1,\n'
  + 'which permits redistribution:\n\n'
  + '- Bricolage Grotesque — https://fonts.google.com/specimen/Bricolage+Grotesque\n'
  + '- Public Sans — https://fonts.google.com/specimen/Public+Sans\n'
  + '- JetBrains Mono — https://fonts.google.com/specimen/JetBrains+Mono\n');

console.log(`\n${kept.length} faces → scripts/social/fonts/`);
